[en]
  languageName = "English"
  languageCode = "en"
  weight = 2
  title = "Vincent's Blog"
  [en.params]
    tagline = "I post stuff related to cybersecurity, sometimes"

[fr]
  languageName = "Français"
  languageCode = "fr"
  weight = 1
  title = "Blog de Vincent"
  [fr.params]
    tagline = "Je publie des choses liés à la cybersécurité, de temps à autre"