baseURL = 'https://vincentperreault.github.io/'
title = "Vincent's Blog"
theme = 'Chirpy'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    locale = 'en'
    label = 'English'
    weight = 1
    languageDirection = 'ltr'

  [languages.fr]
    locale = 'fr'
    label = 'Français'
    weight = 2
    languageDirection = 'ltr'

[params]
  showAuthor = true